### ISSUE TITLE
Warning message from HomeBrew

### ISSUE THREAD

**Issue by jamesrtnz** [samuong/homebrew-alpaca#3]
HomeBrew is now reporting this warning message:

```
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the samuong/alpaca tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/samuong/homebrew-alpaca/alpaca.rb:24
```

**Comment by samuong** [comment]
Thanks for the heads up. I think the solution to this is to replace the `plist_options` call with a [service block](https://docs.brew.sh/Formula-Cookbook#service-files). I'll give that a go and hopefully it fixes this.
